[package]
name = "whisper-tensor"
license = "MIT OR Apache-2.0"
version = "0.1.0"
edition = "2024"
resolver = "2"
readme = "README.md"

[dependencies]
prost = "0.14.3"
serde = { version = "1.0.210", features = ["derive"] }
thiserror = "2.0.12"
anyhow = "1.0.102"
num-traits = "0.2.19"
half = { version="2.5.0", features = ["serde", "num-traits", "zerocopy"] }
tracing-subscriber = { version = "0.3", features = [ "env-filter", "fmt" ] }
tempfile = "3.27.0"
zerocopy = "0.8.42"
tokenizers = {optional=true, version="0.23.1", default-features = false, features = ["unstable_wasm"]}
safetensors = {optional=true, version="0.7.0"}
memmap2 = {optional=true, version="0.9"}
wyrand = "0.4.1"
rand = "0.10.0"
espeak-rs = { version = "0.1.9", optional = true }
zip = "8.2.0"

rayon = "1.10"
rwkv-tokenizer = {workspace=true, optional=true, features = ["serde"] }
env_logger = "0.11.9"
log = "0.4.27"
serde_json = "1.0.140"
ciborium = "0.2.2"
typenum = { version="1.18.0", features=["const-generics"] }
strum = "0.28"
strum_macros = "0.28"
paste = "1.0.15"
image = "0.25"
float8 = { version = "0.7.0", features = ["serde", "num-traits", "zerocopy"] }
arbitrary-int = { version = "2.1", features = ["serde"] }

tch = { version = "0.24.0", optional = true }

dynasm = { version = "5.0", optional = true }
dynasmrt = { version = "5.0", optional = true }

[dev-dependencies]
whisper-tensor-import = {workspace=true}

[features]
default = ["tokenizers", "rwkv-tokenizer", "http", "safetensors", "x86_compile"]
safetensors = ["dep:safetensors", "dep:memmap2"]
tokenizers = ["dep:tokenizers"]
http = ["tokenizers?/http"]
rwkv-tokenizer = ["dep:rwkv-tokenizer"]
x86_compile = ["dep:dynasm", "dep:dynasmrt"]
espeak = ["dep:espeak-rs"]
tch = ["dep:tch"]

[build-dependencies]
prost-build = "0.14.3"

[workspace]
members = [ "crates/whisper-tensor-cli", "crates/whisper-tensor-import", "crates/whisper-tensor-ui", "crates/whisper-tensor-server"]

[workspace.dependencies]
rwkv-tokenizer = { path = "libs/rwkv-tokenizer/rwkv-tokenizer" }
whisper-tensor = {path = "", default-features=false}
whisper-tensor-ui = {path = "crates/whisper-tensor-ui"}
whisper-tensor-import = {path = "crates/whisper-tensor-import"}
whisper-tensor-server = {path = "crates/whisper-tensor-server", default-features=false}


[profile.release-dbg]
inherits = "release"
debug = true
strip = "none"
