//! Model accuracy validation tests.
//!
//! These tests compare whisper-tensor model evaluation against golden reference
//! outputs produced by first-party implementations (ONNX Runtime, HuggingFace
//! transformers, etc.).
//!
//! Golden snapshots are generated by Python scripts in `ci/accuracy/references/`
//! and consist of `.npy` tensor files plus a `manifest.json` describing each
//! tensor's name, dtype, and shape.
//!
//! Tests are skipped when the golden snapshot directory doesn't exist,
//! allowing the test file to be present in the repo without breaking local
//! `cargo test` runs that haven't generated snapshots.

use std::collections::HashMap;
use std::fs;
use std::path::{Path, PathBuf};

use whisper_tensor::model::Model;
use whisper_tensor::npy;
use whisper_tensor::numeric_dtype::NumericDType;
use whisper_tensor::numeric_tensor::{NumericTensor, NumericTensorView, TensorLayout};
use whisper_tensor::pool::{Pool, SystemPool};
use whisper_tensor::tensor_rank::DynRank;
use whisper_tensor_import::onnx_graph::WeightStorageStrategy;

// ---------------------------------------------------------------------------
// Manifest
// ---------------------------------------------------------------------------

#[derive(serde::Deserialize)]
struct Manifest {
    inputs: Vec<TensorEntry>,
    outputs: Vec<TensorEntry>,
}

#[derive(serde::Deserialize)]
struct TensorEntry {
    name: String,
    file: String,
    #[allow(dead_code)]
    dtype: String,
    shape: Vec<u64>,
}

fn load_manifest(dir: &Path) -> Result<Manifest, String> {
    let path = dir.join("manifest.json");
    let data = fs::read_to_string(&path).map_err(|e| format!("Failed to read manifest: {e}"))?;
    serde_json::from_str(&data).map_err(|e| format!("Failed to parse manifest: {e}"))
}

// ---------------------------------------------------------------------------
// Tensor loading from golden snapshots
// ---------------------------------------------------------------------------

fn load_golden_tensors<'p, P: Pool + 'p>(
    dir: &Path,
    entries: &[TensorEntry],
    pool: &'p P,
) -> Result<HashMap<String, NumericTensor<'p, DynRank, P>>, String> {
    let mut tensors = HashMap::new();
    for entry in entries {
        let npy_path = dir.join(&entry.file);
        let tensor = npy::read_npy_file(&npy_path, pool)?;

        // Sanity check shape against manifest
        if tensor.shape().as_slice() != entry.shape.as_slice() {
            return Err(format!(
                "Shape mismatch for '{}': npy {:?} vs manifest {:?}",
                entry.name,
                tensor.shape(),
                entry.shape
            ));
        }

        tensors.insert(entry.name.clone(), tensor);
    }
    Ok(tensors)
}

// ---------------------------------------------------------------------------
// Accuracy comparison
// ---------------------------------------------------------------------------

#[derive(Debug, Clone, serde::Serialize)]
struct TensorAccuracy {
    name: String,
    dtype: String,
    shape: Vec<u64>,
    num_elements: usize,
    max_abs_error: f64,
    mean_abs_error: f64,
    max_rel_error: f64,
    /// Fraction of elements within atol + rtol * |expected|
    within_tolerance: f64,
}

#[derive(Debug, Clone, serde::Serialize)]
struct AccuracyReport {
    model: String,
    pass: bool,
    outputs: Vec<TensorAccuracy>,
}

fn compare_tensor(
    name: &str,
    actual: &NumericTensorView<'_, DynRank>,
    expected: &NumericTensorView<'_, DynRank>,
    rtol: f64,
    atol: f64,
) -> Result<TensorAccuracy, String> {
    let actual_numel = actual.numel();
    let expected_numel = expected.numel();
    if actual_numel != expected_numel {
        return Err(format!(
            "Output '{name}': element count mismatch: actual {:?} ({actual_numel}) vs expected {:?} ({expected_numel})",
            actual.shape(),
            expected.shape()
        ));
    }

    let n = actual_numel;
    let mut max_abs = 0.0f64;
    let mut sum_abs = 0.0f64;
    let mut max_rel = 0.0f64;
    let mut within = 0usize;

    for i in 0..n {
        let a = actual.read_element(i).to_f64();
        let e = expected.read_element(i).to_f64();

        let abs_diff = (a - e).abs();
        max_abs = max_abs.max(abs_diff);
        sum_abs += abs_diff;

        let rel = if e.abs() > 1e-12 {
            abs_diff / e.abs()
        } else {
            0.0
        };
        max_rel = max_rel.max(rel);

        let tolerance = atol + rtol * e.abs();
        if abs_diff <= tolerance {
            within += 1;
        }
    }

    Ok(TensorAccuracy {
        name: name.to_string(),
        dtype: format!("{:?}", actual.dtype()),
        shape: actual.shape().to_vec(),
        num_elements: n,
        max_abs_error: max_abs,
        mean_abs_error: if n > 0 { sum_abs / n as f64 } else { 0.0 },
        max_rel_error: max_rel,
        within_tolerance: if n > 0 { within as f64 / n as f64 } else { 1.0 },
    })
}

// ---------------------------------------------------------------------------
// Test helpers
// ---------------------------------------------------------------------------

/// Returns `true` if the path is a real model file, `false` if it is an LFS pointer.
fn is_real_file(path: &Path) -> bool {
    let Ok(md) = fs::metadata(path) else {
        return false;
    };
    if md.len() < 1024 {
        if let Ok(bytes) = fs::read(path) {
            if bytes.starts_with(b"version https://git-lfs.github.com/spec/v1") {
                return false;
            }
        }
    }
    true
}

fn golden_dir() -> PathBuf {
    if let Ok(dir) = std::env::var("GOLDEN_DIR") {
        PathBuf::from(dir)
    } else {
        let mut dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
        dir.push("ci");
        dir.push("accuracy");
        dir.push("golden");
        dir
    }
}

fn report_dir() -> Option<PathBuf> {
    std::env::var("ACCURACY_REPORT_DIR").ok().map(PathBuf::from)
}

fn write_report(report: &AccuracyReport) {
    let json = serde_json::to_string_pretty(report).unwrap();
    println!("\n=== Accuracy Report: {} ===", report.model);
    for output in &report.outputs {
        println!(
            "  {}: max_abs={:.2e} mean_abs={:.2e} max_rel={:.2e} within_tol={:.4}%",
            output.name,
            output.max_abs_error,
            output.mean_abs_error,
            output.max_rel_error,
            output.within_tolerance * 100.0,
        );
    }
    println!("  RESULT: {}", if report.pass { "PASS" } else { "FAIL" });

    if let Some(dir) = report_dir() {
        let _ = fs::create_dir_all(&dir);
        let path = dir.join(format!("accuracy-{}.json", report.model));
        if let Err(e) = fs::write(&path, &json) {
            eprintln!("Warning: failed to write report to {}: {e}", path.display());
        } else {
            println!("  Report written to {}", path.display());
        }
    }
}

/// Build a zero-filled pool tensor with the given dtype and shape.
fn zero_tensor<'p, P: Pool + 'p>(
    dtype: NumericDType,
    shape: Vec<u64>,
    pool: &'p P,
) -> NumericTensor<'p, DynRank, P> {
    let layout = TensorLayout::<DynRank>::row_major(shape, dtype);
    let buf = pool
        .allocate(layout.buffer_size_bytes())
        .expect("pool allocation for zero tensor");
    // Buffer is already zeroed by SystemPool/TrackedPool.
    NumericTensor::from_parts(buf, layout)
}

/// Run a full accuracy validation for an ONNX model loaded from bytes.
fn validate_onnx_model(
    model_name: &str,
    onnx_data: &[u8],
    golden_path: &Path,
    rtol: f64,
    atol: f64,
    base_dir: Option<&Path>,
) {
    let pool = SystemPool;
    let manifest = load_manifest(golden_path).expect("load manifest");

    let golden_inputs =
        load_golden_tensors(golden_path, &manifest.inputs, &pool).expect("load golden inputs");
    let golden_outputs =
        load_golden_tensors(golden_path, &manifest.outputs, &pool).expect("load golden outputs");

    let mut rng = rand::rng();
    let model = Model::new_from_onnx(onnx_data, &mut rng, base_dir).expect("model loads from ONNX");

    // Prepare inputs: golden snapshot values override model defaults.
    // Inputs NOT in the golden snapshot (e.g., state tensors) get zero-filled.
    let model_input_info = model.get_input_tensor_info().expect("get input info");
    let mut owned_inputs: HashMap<String, NumericTensor<'_, DynRank, SystemPool>> = HashMap::new();

    for (name, (legacy_dtype, shape_desc)) in &model_input_info {
        if golden_inputs.contains_key(name) {
            continue; // Will use golden tensor directly
        }
        let Some(dtype) = NumericDType::from_legacy(*legacy_dtype) else {
            continue; // STRING or Packed — skip
        };
        let concrete_shape: Vec<u64> = shape_desc.iter().map(|d| d.unwrap_or(0)).collect();
        let tensor = zero_tensor(dtype, concrete_shape.clone(), &pool);
        eprintln!("  Auto-filled input '{name}': dtype={dtype:?} shape={concrete_shape:?}");
        owned_inputs.insert(name.clone(), tensor);
    }

    // Build view map for eval_pool: golden inputs + zero-filled inputs.
    let golden_views: HashMap<String, NumericTensorView<'_, DynRank>> = golden_inputs
        .iter()
        .map(|(name, t)| (name.clone(), t.view()))
        .collect();
    let owned_views: HashMap<String, NumericTensorView<'_, DynRank>> = owned_inputs
        .iter()
        .map(|(name, t)| (name.clone(), t.view()))
        .collect();

    let mut input_view_refs: HashMap<String, &NumericTensorView<'_, DynRank>> = HashMap::new();
    for (name, view) in &golden_views {
        input_view_refs.insert(name.clone(), view);
    }
    for (name, view) in &owned_views {
        input_view_refs.insert(name.clone(), view);
    }

    if std::env::var("DUMP_GRAPH").is_ok() {
        let graph = model.get_symbolic_graph();
        let names = graph.get_tensors_by_name();
        let mut names_vec: Vec<_> = names.iter().collect();
        names_vec.sort_by_key(|(n, _)| (*n).clone());
        eprintln!("Named tensors ({}):", names_vec.len());
        for (name, _id) in &names_vec {
            if !name.contains("kv_cache") {
                eprintln!("  {}", name);
            }
        }
    }

    // Run eval
    let actual_outputs = model
        .eval_pool(input_view_refs, &pool)
        .expect("model eval succeeds");

    // Compare each golden output
    let mut output_reports = Vec::new();
    let mut all_pass = true;

    for (name, expected) in &golden_outputs {
        let actual = actual_outputs.get(name).unwrap_or_else(|| {
            panic!(
                "Golden output '{name}' not found in model results. \
                 Model produced: {:?}",
                actual_outputs.keys().collect::<Vec<_>>()
            )
        });

        let acc = compare_tensor(name, &actual.view(), &expected.view(), rtol, atol)
            .unwrap_or_else(|e| panic!("Comparison failed for '{name}': {e}"));

        if acc.within_tolerance < 1.0 {
            eprintln!(
                "WARNING: output '{name}' has {:.2}% elements outside tolerance",
                (1.0 - acc.within_tolerance) * 100.0
            );
            all_pass = false;
        }

        output_reports.push(acc);
    }

    let report = AccuracyReport {
        model: model_name.to_string(),
        pass: all_pass,
        outputs: output_reports,
    };
    write_report(&report);

    assert!(
        all_pass,
        "Accuracy validation failed for {model_name} — see report above"
    );
}

// ---------------------------------------------------------------------------
// GPT-2 accuracy test
// ---------------------------------------------------------------------------

#[test]
fn accuracy_gpt2() {
    let golden_path = golden_dir().join("gpt2");
    if !golden_path.join("manifest.json").exists() {
        eprintln!(
            "Skipping accuracy_gpt2: no golden snapshot at {}",
            golden_path.display()
        );
        eprintln!(
            "Generate with: python ci/accuracy/references/gpt2_onnxrt.py --model test_models/gpt2-lm-head-10.onnx --output {}",
            golden_path.display()
        );
        return;
    }

    let model_path =
        PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("test_models/gpt2-lm-head-10.onnx");
    if !is_real_file(&model_path) {
        eprintln!("Skipping accuracy_gpt2: model file not available (LFS pointer or missing)");
        return;
    }

    let onnx_data = fs::read(&model_path).expect("read model file");

    validate_onnx_model(
        "gpt2",
        &onnx_data,
        &golden_path,
        1e-4, // rtol
        1e-4, // atol
        None,
    );
}

// ---------------------------------------------------------------------------
// RWKV-7 accuracy test
// ---------------------------------------------------------------------------

#[test]
fn accuracy_rwkv7() {
    let golden_path = golden_dir().join("rwkv7");
    if !golden_path.join("manifest.json").exists() {
        eprintln!(
            "Skipping accuracy_rwkv7: no golden snapshot at {}",
            golden_path.display()
        );
        eprintln!(
            "Generate with: python ci/accuracy/references/rwkv7_reference.py --output {}",
            golden_path.display()
        );
        return;
    }

    let pth_path = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("test_models/RWKV-x070-World-0.1B-v2.8-20241210-ctx4096.pth");
    if !is_real_file(&pth_path) {
        eprintln!("Skipping accuracy_rwkv7: model file not available (LFS pointer or missing)");
        return;
    }

    let onnx_data =
        whisper_tensor_import::identify_and_load(&pth_path, WeightStorageStrategy::EmbeddedData)
            .expect("import rwkv7 .pth to ONNX");

    validate_onnx_model(
        "rwkv7",
        &onnx_data,
        &golden_path,
        1e-3, // rtol
        1e-4, // atol
        None,
    );
}

// ---------------------------------------------------------------------------
// HuggingFace transformers model accuracy tests
// ---------------------------------------------------------------------------

macro_rules! hf_accuracy_test {
    ($test_name:ident, $model_name:expr, $ceph_subpath:expr, $rtol:expr, $atol:expr) => {
        #[test]
        fn $test_name() {
            let golden_path = golden_dir().join($model_name);
            if !golden_path.join("manifest.json").exists() {
                eprintln!(
                    "Skipping {}: no golden snapshot at {}",
                    stringify!($test_name),
                    golden_path.display()
                );
                eprintln!(
                    "Generate with: python ci/accuracy/references/hf_causal_lm.py --model /path/to/{} --output {}",
                    $ceph_subpath, golden_path.display()
                );
                return;
            }

            let model_dir = [
                format!("/models/llms/{}", $ceph_subpath),
                format!("/ceph/public/neural_models/llms/{}", $ceph_subpath),
            ]
            .iter()
            .map(PathBuf::from)
            .find(|p| p.join("config.json").exists());

            let Some(model_dir) = model_dir else {
                eprintln!(
                    "Skipping {}: {} not found on Ceph",
                    stringify!($test_name),
                    $ceph_subpath
                );
                return;
            };

            let onnx_data = whisper_tensor_import::identify_and_load(
                &model_dir,
                WeightStorageStrategy::EmbeddedData,
            )
            .unwrap_or_else(|e| panic!("import {} to ONNX failed: {e}", $ceph_subpath));

            validate_onnx_model(
                $model_name,
                &onnx_data,
                &golden_path,
                $rtol,
                $atol,
                Some(&model_dir),
            );
        }
    };
}

// BF16 models: atol=1e-2 covers the minimum BF16 quantum (~0.0078).
hf_accuracy_test!(accuracy_qwen2_05b, "qwen2_05b", "Qwen2-0.5B", 1e-2, 1e-2);
hf_accuracy_test!(accuracy_qwen3_06b, "qwen3_06b", "Qwen3-0.6B", 1e-2, 1e-2);
hf_accuracy_test!(accuracy_gemma2_2b, "gemma2_2b", "gemma-2-2b-it", 1e-2, 1e-2);
hf_accuracy_test!(accuracy_llama3_8b, "llama3_8b", "Llama-3-8B", 1e-2, 1e-2);
hf_accuracy_test!(
    accuracy_mistral_7b,
    "mistral_7b",
    "mistralai_Mistral-7B-v0.1",
    1e-2,
    1e-2
);
hf_accuracy_test!(
    accuracy_phi3_mini,
    "phi3_mini",
    "Phi-3-mini-4k-instruct-model",
    1e-2,
    1e-2
);
