//! Model accuracy validation tests.
//!
//! These tests compare whisper-tensor model evaluation against golden reference
//! outputs produced by first-party implementations (ONNX Runtime, HuggingFace
//! transformers, etc.).
//!
//! Golden snapshots are generated by Python scripts in `ci/accuracy/references/`
//! and consist of `.npy` tensor files plus a `manifest.json` describing each
//! tensor's name, dtype, and shape.
//!
//! Tests are skipped when the golden snapshot directory doesn't exist,
//! allowing the test file to be present in the repo without breaking local
//! `cargo test` runs that haven't generated snapshots.

use std::collections::HashMap;
use std::fs;
use std::path::{Path, PathBuf};

use whisper_tensor::backends::eval_backend::EvalBackend;
use whisper_tensor::backends::ndarray_backend::NDArrayNumericTensor;
use whisper_tensor::dtype::DType;
use whisper_tensor::model::{Model, ModelExecutionRuntime};
use whisper_tensor::numeric_tensor::NumericTensor;
use whisper_tensor::tensor_rank::DynRank;
use whisper_tensor_import::onnx_graph::WeightStorageStrategy;

// ---------------------------------------------------------------------------
// .npy reader
// ---------------------------------------------------------------------------

/// Minimal NumPy .npy file reader.
///
/// Supports the subset of dtypes we care about: float32, float64, int32, int64,
/// float16. The .npy format is: 6-byte magic, 2-byte version, 2-byte header
/// length, ASCII header with dtype/shape/order, then raw data.
fn read_npy(path: &Path) -> Result<(DType, Vec<u64>, Vec<u8>), String> {
    let data = fs::read(path).map_err(|e| format!("Failed to read {}: {e}", path.display()))?;

    // Validate magic: \x93NUMPY
    if data.len() < 10 || &data[..6] != b"\x93NUMPY" {
        return Err(format!("Not a valid .npy file: {}", path.display()));
    }

    let major = data[6];
    let header_len = if major >= 2 {
        // v2+: 4-byte little-endian header length
        if data.len() < 12 {
            return Err("Truncated v2 npy header".into());
        }
        u32::from_le_bytes([data[8], data[9], data[10], data[11]]) as usize
    } else {
        // v1: 2-byte little-endian header length
        u16::from_le_bytes([data[8], data[9]]) as usize
    };

    let header_start = if major >= 2 { 12 } else { 10 };
    let header_end = header_start + header_len;
    if data.len() < header_end {
        return Err("Truncated npy header".into());
    }

    let header =
        std::str::from_utf8(&data[header_start..header_end]).map_err(|e| format!("{e}"))?;

    // Parse dtype from header: 'descr': '<f4', etc.
    let dtype = parse_npy_dtype(header)?;

    // Parse shape from header: 'shape': (4, 4, 50257), etc.
    let shape = parse_npy_shape(header)?;

    let raw = data[header_end..].to_vec();
    Ok((dtype, shape, raw))
}

fn parse_npy_dtype(header: &str) -> Result<DType, String> {
    // Find 'descr' value — look for the pattern 'descr': '...'
    let descr_start = header
        .find("'descr'")
        .or_else(|| header.find("\"descr\""))
        .ok_or("No 'descr' in npy header")?;
    let rest = &header[descr_start..];

    // Extract the dtype string between quotes after the colon
    let colon = rest.find(':').ok_or("No colon after descr")?;
    let after_colon = &rest[colon + 1..];
    let quote_char = if after_colon.contains('\'') {
        '\''
    } else {
        '"'
    };
    let first_quote = after_colon
        .find(quote_char)
        .ok_or("No opening quote for descr value")?;
    let inner = &after_colon[first_quote + 1..];
    let end_quote = inner
        .find(quote_char)
        .ok_or("No closing quote for descr value")?;
    let descr = &inner[..end_quote];

    // Strip endianness prefix (< or > or =) if present
    let type_str = descr.trim_start_matches(['<', '>', '=', '|']);

    match type_str {
        "f8" => Ok(DType::F64),
        "f4" => Ok(DType::F32),
        "f2" => Ok(DType::F16),
        "i8" => Ok(DType::I64),
        "i4" => Ok(DType::I32),
        "i2" => Ok(DType::I16),
        "i1" => Ok(DType::I8),
        "u8" => Ok(DType::U64),
        "u4" => Ok(DType::U32),
        "u2" => Ok(DType::U16),
        "u1" => Ok(DType::U8),
        "b1" => Ok(DType::BOOL),
        "float64" => Ok(DType::F64),
        "float32" => Ok(DType::F32),
        "float16" => Ok(DType::F16),
        "int64" => Ok(DType::I64),
        "int32" => Ok(DType::I32),
        "int16" => Ok(DType::I16),
        "int8" => Ok(DType::I8),
        "uint64" => Ok(DType::U64),
        "uint32" => Ok(DType::U32),
        "uint16" => Ok(DType::U16),
        "uint8" => Ok(DType::U8),
        other => Err(format!("Unsupported npy dtype: {other}")),
    }
}

fn parse_npy_shape(header: &str) -> Result<Vec<u64>, String> {
    let shape_start = header
        .find("'shape'")
        .or_else(|| header.find("\"shape\""))
        .ok_or("No 'shape' in npy header")?;
    let rest = &header[shape_start..];
    let open = rest.find('(').ok_or("No '(' in shape")?;
    let close = rest.find(')').ok_or("No ')' in shape")?;
    let inner = rest[open + 1..close].trim();

    if inner.is_empty() {
        // Scalar: shape ()
        return Ok(vec![]);
    }

    inner
        .split(',')
        .map(|s| s.trim())
        .filter(|s| !s.is_empty())
        .map(|s| {
            s.parse::<u64>()
                .map_err(|e| format!("Bad shape dim '{s}': {e}"))
        })
        .collect()
}

// ---------------------------------------------------------------------------
// Manifest
// ---------------------------------------------------------------------------

#[derive(serde::Deserialize)]
struct Manifest {
    inputs: Vec<TensorEntry>,
    outputs: Vec<TensorEntry>,
}

#[derive(serde::Deserialize)]
struct TensorEntry {
    name: String,
    file: String,
    #[allow(dead_code)]
    dtype: String,
    shape: Vec<u64>,
}

fn load_manifest(dir: &Path) -> Result<Manifest, String> {
    let path = dir.join("manifest.json");
    let data = fs::read_to_string(&path).map_err(|e| format!("Failed to read manifest: {e}"))?;
    serde_json::from_str(&data).map_err(|e| format!("Failed to parse manifest: {e}"))
}

// ---------------------------------------------------------------------------
// Tensor loading from golden snapshots
// ---------------------------------------------------------------------------

fn load_golden_tensors(
    dir: &Path,
    entries: &[TensorEntry],
) -> Result<HashMap<String, NumericTensor<DynRank>>, String> {
    let mut tensors = HashMap::new();
    for entry in entries {
        let npy_path = dir.join(&entry.file);
        let (dtype, shape, raw_data) = read_npy(&npy_path)?;

        // Sanity check against manifest
        if shape != entry.shape {
            return Err(format!(
                "Shape mismatch for '{}': npy {:?} vs manifest {:?}",
                entry.name, shape, entry.shape
            ));
        }

        let nd = NDArrayNumericTensor::from_raw_data(&raw_data, dtype, shape)
            .map_err(|e| format!("Failed to build tensor '{}': {e}", entry.name))?;
        tensors.insert(entry.name.clone(), NumericTensor::NDArray(nd));
    }
    Ok(tensors)
}

// ---------------------------------------------------------------------------
// Accuracy comparison
// ---------------------------------------------------------------------------

#[derive(Debug, Clone, serde::Serialize)]
struct TensorAccuracy {
    name: String,
    dtype: String,
    shape: Vec<u64>,
    num_elements: usize,
    max_abs_error: f64,
    mean_abs_error: f64,
    max_rel_error: f64,
    /// Fraction of elements within atol + rtol * |expected|
    within_tolerance: f64,
}

#[derive(Debug, Clone, serde::Serialize)]
struct AccuracyReport {
    model: String,
    pass: bool,
    outputs: Vec<TensorAccuracy>,
}

fn compare_tensor(
    name: &str,
    actual: &NumericTensor<DynRank>,
    expected: &NumericTensor<DynRank>,
    rtol: f64,
    atol: f64,
) -> Result<TensorAccuracy, String> {
    // Compare element counts rather than exact shapes — the ONNX graph may
    // retain batch/unsqueeze dims that the reference squeezes away.
    let actual_numel: u64 = actual.shape().iter().product();
    let expected_numel: u64 = expected.shape().iter().product();
    if actual_numel != expected_numel {
        return Err(format!(
            "Output '{name}': element count mismatch: actual {:?} ({actual_numel}) vs expected {:?} ({expected_numel})",
            actual.shape(),
            expected.shape()
        ));
    }

    let actual_f64: Vec<f64> = actual
        .cast(DType::F64, &mut EvalBackend::NDArray)
        .map_err(|e| format!("cast actual: {e}"))?
        .to_ndarray()
        .map_err(|e| format!("to_ndarray actual: {e}"))?
        .flatten()
        .try_to_vec()
        .map_err(|e| format!("to_vec actual: {e}"))?;

    let expected_f64: Vec<f64> = expected
        .cast(DType::F64, &mut EvalBackend::NDArray)
        .map_err(|e| format!("cast expected: {e}"))?
        .to_ndarray()
        .map_err(|e| format!("to_ndarray expected: {e}"))?
        .flatten()
        .try_to_vec()
        .map_err(|e| format!("to_vec expected: {e}"))?;

    let n = actual_f64.len();
    if n != expected_f64.len() {
        return Err(format!(
            "Output '{name}': element count mismatch: {} vs {}",
            n,
            expected_f64.len()
        ));
    }

    let mut max_abs = 0.0f64;
    let mut sum_abs = 0.0f64;
    let mut max_rel = 0.0f64;
    let mut within = 0usize;

    for (a, e) in actual_f64.iter().zip(expected_f64.iter()) {
        let abs_diff = (a - e).abs();
        max_abs = max_abs.max(abs_diff);
        sum_abs += abs_diff;

        let rel = if e.abs() > 1e-12 {
            abs_diff / e.abs()
        } else {
            0.0
        };
        max_rel = max_rel.max(rel);

        let tolerance = atol + rtol * e.abs();
        if abs_diff <= tolerance {
            within += 1;
        }
    }

    Ok(TensorAccuracy {
        name: name.to_string(),
        dtype: format!("{:?}", actual.dtype()),
        shape: actual.shape().to_vec(),
        num_elements: n,
        max_abs_error: max_abs,
        mean_abs_error: if n > 0 { sum_abs / n as f64 } else { 0.0 },
        max_rel_error: max_rel,
        within_tolerance: if n > 0 { within as f64 / n as f64 } else { 1.0 },
    })
}

// ---------------------------------------------------------------------------
// Test helpers
// ---------------------------------------------------------------------------

/// Returns `true` if the path is a real model file, `false` if it is an LFS pointer.
fn is_real_file(path: &Path) -> bool {
    let Ok(md) = fs::metadata(path) else {
        return false;
    };
    if md.len() < 1024 {
        if let Ok(bytes) = fs::read(path) {
            if bytes.starts_with(b"version https://git-lfs.github.com/spec/v1") {
                return false;
            }
        }
    }
    true
}

fn golden_dir() -> PathBuf {
    if let Ok(dir) = std::env::var("GOLDEN_DIR") {
        PathBuf::from(dir)
    } else {
        // Default: ci/accuracy/golden/ relative to repo root
        let mut dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
        dir.push("ci");
        dir.push("accuracy");
        dir.push("golden");
        dir
    }
}

fn report_dir() -> Option<PathBuf> {
    std::env::var("ACCURACY_REPORT_DIR").ok().map(PathBuf::from)
}

fn write_report(report: &AccuracyReport) {
    // Always print to stdout
    let json = serde_json::to_string_pretty(report).unwrap();
    println!("\n=== Accuracy Report: {} ===", report.model);
    for output in &report.outputs {
        println!(
            "  {}: max_abs={:.2e} mean_abs={:.2e} max_rel={:.2e} within_tol={:.4}%",
            output.name,
            output.max_abs_error,
            output.mean_abs_error,
            output.max_rel_error,
            output.within_tolerance * 100.0,
        );
    }
    println!("  RESULT: {}", if report.pass { "PASS" } else { "FAIL" });

    // Optionally write JSON artifact
    if let Some(dir) = report_dir() {
        let _ = fs::create_dir_all(&dir);
        let path = dir.join(format!("accuracy-{}.json", report.model));
        if let Err(e) = fs::write(&path, &json) {
            eprintln!("Warning: failed to write report to {}: {e}", path.display());
        } else {
            println!("  Report written to {}", path.display());
        }
    }
}

/// Run a full accuracy validation for an ONNX model loaded from bytes.
fn validate_onnx_model(
    model_name: &str,
    onnx_data: &[u8],
    golden_path: &Path,
    rtol: f64,
    atol: f64,
    base_dir: Option<&Path>,
) {
    let manifest = load_manifest(golden_path).expect("load manifest");

    // Load golden inputs and expected outputs
    let golden_inputs =
        load_golden_tensors(golden_path, &manifest.inputs).expect("load golden inputs");
    let golden_outputs =
        load_golden_tensors(golden_path, &manifest.outputs).expect("load golden outputs");

    // Load model
    let mut rng = rand::rng();
    let model = Model::new_from_onnx(onnx_data, &mut rng, base_dir).expect("model loads from ONNX");

    // Prepare inputs: match golden input names to model input names.
    // Inputs present in the golden snapshot override model defaults.
    // Inputs NOT in the golden snapshot (e.g., state tensors with zero initializers)
    // are left for the model to fill from its ONNX initializers.
    let model_input_info = model.get_input_tensor_info().expect("get input info");
    let mut inputs: HashMap<String, NumericTensor<DynRank>> = HashMap::new();
    for (name, (dtype, shape)) in &model_input_info {
        if let Some(tensor) = golden_inputs.get(name) {
            inputs.insert(name.clone(), tensor.clone());
        } else {
            // Build zero tensor for inputs not in golden snapshot.
            // Replace dynamic (None) dims with 0 for cache-like inputs,
            // or 1 for other dims.
            let concrete_shape: Vec<u64> = shape.iter().map(|d| d.unwrap_or(0)).collect();
            let numel: usize = concrete_shape.iter().product::<u64>() as usize;
            if let Some(elem_size) = dtype.bytes_per_element() {
                let zeros = vec![0u8; numel * elem_size];
                if let Ok(nd) =
                    NDArrayNumericTensor::from_raw_data(&zeros, *dtype, concrete_shape.clone())
                {
                    inputs.insert(name.clone(), NumericTensor::NDArray(nd));
                    eprintln!(
                        "  Auto-filled input '{name}': dtype={dtype:?} shape={concrete_shape:?}"
                    );
                }
            }
        }
    }

    // Run eval
    let mut runtime = ModelExecutionRuntime::Eval(EvalBackend::NDArray);
    let actual_outputs = model
        .run(inputs, &mut (), &mut runtime)
        .expect("model eval succeeds");

    // Compare each golden output
    let mut output_reports = Vec::new();
    let mut all_pass = true;

    for (name, expected) in &golden_outputs {
        let actual = actual_outputs.get(name).unwrap_or_else(|| {
            panic!(
                "Golden output '{name}' not found in model results. \
                 Model produced: {:?}",
                actual_outputs.keys().collect::<Vec<_>>()
            )
        });

        let acc = compare_tensor(name, actual, expected, rtol, atol)
            .unwrap_or_else(|e| panic!("Comparison failed for '{name}': {e}"));

        if acc.within_tolerance < 1.0 {
            eprintln!(
                "WARNING: output '{name}' has {:.2}% elements outside tolerance",
                (1.0 - acc.within_tolerance) * 100.0
            );
            all_pass = false;
        }

        output_reports.push(acc);
    }

    let report = AccuracyReport {
        model: model_name.to_string(),
        pass: all_pass,
        outputs: output_reports,
    };
    write_report(&report);

    assert!(
        all_pass,
        "Accuracy validation failed for {model_name} — see report above"
    );
}

// ---------------------------------------------------------------------------
// GPT-2 accuracy test
// ---------------------------------------------------------------------------

#[test]
fn accuracy_gpt2() {
    let golden_path = golden_dir().join("gpt2");
    if !golden_path.join("manifest.json").exists() {
        eprintln!(
            "Skipping accuracy_gpt2: no golden snapshot at {}",
            golden_path.display()
        );
        eprintln!(
            "Generate with: python ci/accuracy/references/gpt2_onnxrt.py --model test_models/gpt2-lm-head-10.onnx --output {}",
            golden_path.display()
        );
        return;
    }

    let model_path =
        PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("test_models/gpt2-lm-head-10.onnx");
    if !is_real_file(&model_path) {
        eprintln!("Skipping accuracy_gpt2: model file not available (LFS pointer or missing)");
        return;
    }

    let onnx_data = fs::read(&model_path).expect("read model file");

    // GPT-2 ONNX via onnxruntime reference: expect very tight match (same graph, same ops)
    validate_onnx_model(
        "gpt2",
        &onnx_data,
        &golden_path,
        1e-5, // rtol
        1e-5, // atol
        None,
    );
}

// ---------------------------------------------------------------------------
// RWKV-7 accuracy test
// ---------------------------------------------------------------------------

#[test]
fn accuracy_rwkv7() {
    let golden_path = golden_dir().join("rwkv7");
    if !golden_path.join("manifest.json").exists() {
        eprintln!(
            "Skipping accuracy_rwkv7: no golden snapshot at {}",
            golden_path.display()
        );
        eprintln!(
            "Generate with: python ci/accuracy/references/rwkv7_reference.py --output {}",
            golden_path.display()
        );
        return;
    }

    let pth_path = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("test_models/RWKV-x070-World-0.1B-v2.8-20241210-ctx4096.pth");
    if !is_real_file(&pth_path) {
        eprintln!("Skipping accuracy_rwkv7: model file not available (LFS pointer or missing)");
        return;
    }

    // Convert .pth → ONNX via the importer (this is part of what we're validating)
    let onnx_data =
        whisper_tensor_import::identify_and_load(&pth_path, WeightStorageStrategy::EmbeddedData)
            .expect("import rwkv7 .pth to ONNX");

    // RWKV-7 reference is the official PyTorch implementation.
    // Wider tolerance than GPT-2 because we're comparing across two different
    // implementations (PyTorch reference vs our ONNX graph builder + NDArray eval),
    // not just the same ONNX graph through two runtimes.
    validate_onnx_model(
        "rwkv7",
        &onnx_data,
        &golden_path,
        1e-3, // rtol
        1e-4, // atol
        None,
    );
}

// ---------------------------------------------------------------------------
// HuggingFace transformers model accuracy tests
// ---------------------------------------------------------------------------
// All HF models follow the same pattern: find model dir on Ceph,
// import via identify_and_load(), compare logits to golden snapshot.

/// Generate an accuracy test for a HuggingFace transformers model on Ceph.
macro_rules! hf_accuracy_test {
    ($test_name:ident, $model_name:expr, $ceph_subpath:expr, $rtol:expr, $atol:expr) => {
        #[test]
        fn $test_name() {
            let golden_path = golden_dir().join($model_name);
            if !golden_path.join("manifest.json").exists() {
                eprintln!(
                    "Skipping {}: no golden snapshot at {}",
                    stringify!($test_name),
                    golden_path.display()
                );
                eprintln!(
                    "Generate with: python ci/accuracy/references/hf_causal_lm.py --model /path/to/{} --output {}",
                    $ceph_subpath, golden_path.display()
                );
                return;
            }

            let model_dir = [
                format!("/models/llms/{}", $ceph_subpath),
                format!("/ceph/public/neural_models/llms/{}", $ceph_subpath),
            ]
            .iter()
            .map(PathBuf::from)
            .find(|p| p.join("config.json").exists());

            let Some(model_dir) = model_dir else {
                eprintln!(
                    "Skipping {}: {} not found on Ceph",
                    stringify!($test_name),
                    $ceph_subpath
                );
                return;
            };

            let onnx_data = whisper_tensor_import::identify_and_load(
                &model_dir,
                WeightStorageStrategy::EmbeddedData,
            )
            .unwrap_or_else(|e| panic!("import {} to ONNX failed: {e}", $ceph_subpath));

            validate_onnx_model(
                $model_name,
                &onnx_data,
                &golden_path,
                $rtol,
                $atol,
                Some(&model_dir),
            );
        }
    };
}

// Qwen2 0.5B — smallest Qwen2, BF16
hf_accuracy_test!(accuracy_qwen2_05b, "qwen2_05b", "Qwen2-0.5B", 1e-2, 1e-3);

// Qwen3 0.6B — smallest Qwen3
hf_accuracy_test!(accuracy_qwen3_06b, "qwen3_06b", "Qwen3-0.6B", 1e-2, 1e-3);

// Gemma 2 2B
hf_accuracy_test!(accuracy_gemma2_2b, "gemma2_2b", "gemma-2-2b-it", 1e-2, 1e-3);

// Llama 3 8B
hf_accuracy_test!(accuracy_llama3_8b, "llama3_8b", "Llama-3-8B", 1e-2, 1e-3);

// Mistral 7B v0.1
hf_accuracy_test!(
    accuracy_mistral_7b,
    "mistral_7b",
    "mistralai_Mistral-7B-v0.1",
    1e-2,
    1e-3
);

// Phi-3 mini 4k
hf_accuracy_test!(
    accuracy_phi3_mini,
    "phi3_mini",
    "Phi-3-mini-4k-instruct-model",
    1e-2,
    1e-3
);
