mod auto;
mod f5_tts;
mod flux;
mod gguf;
mod kokoro;
mod onnx;
mod piper;
mod rwkv7;
mod sd15;
mod sd2;
mod sd35;
mod sd_xl;
mod shared;
mod transformers;
mod whisper;

pub use self::auto::AutoLoader;
pub use self::f5_tts::F5TtsLoader;
pub use self::flux::FluxLoader;
pub use self::gguf::GgufLoader;
pub use self::kokoro::KokoroLoader;
pub use self::onnx::OnnxLoader;
pub use self::piper::PiperLoader;
pub use self::rwkv7::Rwkv7Loader;
pub use self::sd_xl::SDXLLoader;
pub use self::sd2::SD2Loader;
pub use self::sd15::SD15Loader;
pub use self::sd35::SD35Loader;
pub use self::transformers::TransformersLoader;
pub use self::whisper::WhisperLoader;
