[alias]
fmt-nolibs = "fmt -p whisper-tensor -p whisper-tensor-import -p whisper-tensor-server -p whisper-tensor-webui"
fmtcheck-nolibs = "fmt -p whisper-tensor -p whisper-tensor-import -p whisper-tensor-server -p whisper-tensor-webui -- --check"
