name: WebUI WASM Build

on:
  push:
    branches: [ "main" ]
    paths:
      - "crates/whisper-tensor-webui/**"
      - "src/**"                   # root crate source used by the webui
      - "crates/**"                # any other workspace crates
      - "Cargo.toml"
      - "Cargo.lock"
      - "build.rs"
      - ".github/workflows/webui-wasm.yml"
  pull_request:
    branches: [ "main" ]
    paths:
      - "crates/whisper-tensor-webui/**"
      - "src/**"
      - "crates/**"
      - "Cargo.toml"
      - "Cargo.lock"
      - "build.rs"
      - ".github/workflows/webui-wasm.yml"

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: '--cfg getrandom_backend="wasm_js"'
  CARGO_TARGET_DIR: target

jobs:
  build-wasm:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Rust (stable) + wasm32 target
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown

      # protoc for prost-build (runs in build.rs)
      - name: Install protoc
        uses: arduino/setup-protoc@v2
        with:
          version: "28.x"   # modern protoc; adjust if you need to pin

      - name: Cache cargo (registry, git, target)
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-wasm-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-wasm-

      - name: Cache wasm-pack tool cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/.wasm-pack
          key: ${{ runner.os }}-wasm-pack-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-wasm-pack-

      - name: Install wasm-pack
        uses: jetli/wasm-pack-action@v0.3.0
        with:
          version: 'latest'  # pin if you prefer

      - name: Build webui crate (wasm)
        working-directory: crates/whisper-tensor-webui
        run: |
          wasm-pack build --target web --locked
          # If your workspace defaults pull in native-only features, use:
          # wasm-pack build --target web --locked -- --no-default-features --features web
